options:
  virtual-ip:
    type: string
    default: ""
    description: |
      Virtual IP/netmask that will be moved between instances,
      e.g.: 10.1.2.3/16
  router-id:
    type: int
    default: 23
    description: |
      Virtual router identifier - a number between 1 and 255
      that's unique within the network segment
  network-interface:
    type: string
    description: |
      Network interface name for the VIP
