options:
  virtual_ip:
    type: string
    default: ""
    description: |
      Virtual IP/netmask that will be moved between instances,
      e.g.: 10.1.2.3/16
  vip_hostname:
    type: string
    default: ""
    description: |
      A VIP hostname to pass to clients.
  port:
    type: int
    default: 443
    description: |
      A port to pass to clients.
  router_id:
    type: int
    default: 23
    description: |
      Virtual router identifier - a number between 1 and 255
      that's unique within the network segment
  network_interface:
    type: string
    default: ""
    description: |
      Network interface name for the VIP. The default value is
      the result of running the following command:
      `route | grep default | head -n 1 | awk {'print $8'}`.
